name: newspaper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scipy
  - pymongdo
  - mongodb
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - dash
  - jupyterlab
  - jupyter
  - nltk
