FROM python:3.8-alpine

COPY ./requirements.txt ./requirements.txt
COPY job.py job.py

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Configure cron
COPY crontab /etc/cron/crontab

RUN chmod 0644 /etc/cron/crontab
# Init cron
RUN crontab /etc/cron/crontab

CMD ["crond", "-f"]