FROM ubuntu:latest
FROM python:3.7

ADD ./requirements.txt ./requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

USER root

ADD . .
ADD crontab /etc/cron.d/crontab

RUN    apt-get update
RUN    apt-get install -y cron
RUN    chmod 0644 /etc/cron.d/crontab
RUN    chmod +x run.sh
RUN    chmod +x job.py
RUN    touch /var/log/cron.log

CMD ./run.sh